### ISSUE TITLE
Geyser Compatibility

### ISSUE THREAD

**Issue by IAmNotLiable** [onebeastchris/visitors#12]
Hey, 
I'm still loving the mod, but when I have bedrock players joining through Geyser (via Velocity) they go back to spectator mode once they log out and log back in instead of survival mode. I rarely get Xbox players on my server, but if any do take an active interest I would still like to be able to use this mod. I realize it's very niche and requires some extra hardware to test and verify, so if there is anything I can do to help troubleshoot this, please let me know.  I realize it's very niche and requires some extra hardware to test and verify.

**Comment by onebeastchris** [comment]
Hey 👋
Last I checked, Geyser/Floodgate should be perfectly compatible with this little mod. The only reason for why a player would be back in spectator mode would be that they're not on the whitelist - did you use the /fwhitelist add command from floodgate to add Bedrock players to the whitelist?

You can also double-check your whitelist.json file manually for whether there's an entry for said Bedrock players.

**Comment by IAmNotLiable** [comment]
Thank you Chris! I don't get a lot of Bedrock players, so I wasn't even aware of the /fwhitelist command. It totally works, Thanks!!!

**Comment by onebeastchris** [comment]
excellent, will close as complete :)
