### ISSUE TITLE
whitelisting sets wrong gamemode

### ISSUE THREAD

**Issue by 909oce** [onebeastchris/visitors#19]
my server.properties has default gamemode set to creative, however when i whitelist someone they are still sent to survival mode. please let me know if theres something im doing wrong or a if its a bug in the newest version

**Comment by onebeastchris** [comment]
Interesting, that's something that should be accounted for; see here:
https://github.com/onebeastchris/visitors/blob/master/src%2Fmain%2Fjava%2Fonebeastchris%2Fevent%2FServerLeaveEvent.java#L34

I'll spin up a test server and see if I can replicate that behavior tomorrow

**Comment by 909oce** [comment]
I just double checked it and also did /defaultgamemode creative one more time, but it still put me into survival. let me know what your test server outcome is

**Comment by onebeastchris** [comment]
Was able to replicate; thanks for the bug report. Apparently, GameMode.DEFAULT is just a front for survival, and not the actual default gamemode..
https://github.com/onebeastchris/visitors/commit/0c86dba8bd34508ba18c47a4e272347b7df44e1b fixes it, and is available on modrinth as version 1.0.3 now :)

**Comment by 909oce** [comment]
Thank you!
