### ISSUE TITLE
[Enhance] Tp the player back to spawn before switching gamode to survival

### ISSUE THREAD

**Issue by OscarVsp** [onebeastchris/visitors#20]
Hello !

First of all, thanks for this mod.

I think it would be nice to have the option to teleport the player to the spawn when he's whitelisted, before changing the gamemode.

This would prevent them from dying by falling from a high place when switching from spectator tor survival mode.

Happy new year !

**Comment by onebeastchris** [comment]
Hey, thanks for the bug report.

https://github.com/onebeastchris/visitors/blob/1.20/src%2Fmain%2Fjava%2Fonebeastchris%2Fevent%2FServerLeaveEvent.java#L33-L34
This mod already does teleport the player before changing the game mode, so I'm not entirely sure how a player could die?

Is your spawn point somewhere up in the air, or similar? In which case it might be possible to give the player some sort of brief immunity

**Comment by onebeastchris** [comment]
Closing due to no response.
